In [1]:
from bs4 import BeautifulSoup
from datetime import date
import requests,lxml
import pandas as pd
import numpy as np

In [2]:
html_text = requests.get("https://www.ipttc.org/rating/").text

In [3]:
soup=BeautifulSoup(html_text,"lxml")
ranking_month = soup.find_all("td")
#print(ranking_month)
links=[]
for i in range(len(ranking_month)): 
    if i %2 ==0:
        link=ranking_month[i].a["href"]
        links=links+[link]

In [4]:
overall=pd.DataFrame({"link":links})
overall["men_wheelchair"]="https://www.ipttc.org/rating/"+overall["link"].str.slice(stop=10)+"/Men_in_wheelchair.htm"
overall["women_wheelchair"]="https://www.ipttc.org/rating/"+overall["link"].str.slice(stop=10)+"/Women_in_wheelchair.htm"
overall["men_standing"]="https://www.ipttc.org/rating/"+overall["link"].str.slice(stop=10)+"/Men_standing.htm"
overall["women_standing"]="https://www.ipttc.org/rating/"+overall["link"].str.slice(stop=10)+"/Women_standing.htm"
overall["month"]=overall["link"].str.slice(stop=10)

In [5]:
overall

,link,men_wheelchair,women_wheelchair,men_standing,women_standing,month
0,2020-04-01/index.htm,https://www.ipttc.org/rating/2020-04-01/Men_in...,https://www.ipttc.org/rating/2020-04-01/Women_...,https://www.ipttc.org/rating/2020-04-01/Men_st...,https://www.ipttc.org/rating/2020-04-01/Women_...,2020-04-01
1,2020-03-01/index.htm,https://www.ipttc.org/rating/2020-03-01/Men_in...,https://www.ipttc.org/rating/2020-03-01/Women_...,https://www.ipttc.org/rating/2020-03-01/Men_st...,https://www.ipttc.org/rating/2020-03-01/Women_...,2020-03-01
2,2020-02-01/index.htm,https://www.ipttc.org/rating/2020-02-01/Men_in...,https://www.ipttc.org/rating/2020-02-01/Women_...,https://www.ipttc.org/rating/2020-02-01/Men_st...,https://www.ipttc.org/rating/2020-02-01/Women_...,2020-02-01
3,2020-01-01/index.htm,https://www.ipttc.org/rating/2020-01-01/Men_in...,https://www.ipttc.org/rating/2020-01-01/Women_...,https://www.ipttc.org/rating/2020-01-01/Men_st...,https://www.ipttc.org/rating/2020-01-01/Women_...,2020-01-01
4,2019-12-01/index.htm,https://www.ipttc.org/rating/2019-12-01/Men_in...,https://www.ipttc.org/rating/2019-12-01/Women_...,https://www.ipttc.org/rating/2019-12-01/Men_st...,https://www.ipttc.org/rating/2019-12-01/Women_...,2019-12-01
...,...,...,...,...,...,...
72,2013-01-01/index.htm,https://www.ipttc.org/rating/2013-01-01/Men_in...,https://www.ipttc.org/rating/2013-01-01/Women_...,https://www.ipttc.org/rating/2013-01-01/Men_st...,https://www.ipttc.org/rating/2013-01-01/Women_...,2013-01-01
73,2012-10-01/index.htm,https://www.ipttc.org/rating/2012-10-01/Men_in...,https://www.ipttc.org/rating/2012-10-01/Women_...,https://www.ipttc.org/rating/2012-10-01/Men_st...,https://www.ipttc.org/rating/2012-10-01/Women_...,2012-10-01
74,2012-07-01/index.htm,https://www.ipttc.org/rating/2012-07-01/Men_in...,https://www.ipttc.org/rating/2012-07-01/Women_...,https://www.ipttc.org/rating/2012-07-01/Men_st...,https://www.ipttc.org/rating/2012-07-01/Women_...,2012-07-01
75,2012-04-01/index.htm,https://www.ipttc.org/rating/2012-04-01/Men_in...,https://www.ipttc.org/rating/2012-04-01/Women_...,https://www.ipttc.org/rating/2012-04-01/Men_st...,https://www.ipttc.org/rating/2012-04-01/Women_...,2012-04-01
76,2012-01-01/index.htm,https://www.ipttc.org/rating/2012-01-01/Men_in...,https://www.ipttc.org/rating/2012-01-01/Women_...,https://www.ipttc.org/rating/2012-01-01/Men_st...,https://www.ipttc.org/rating/2012-01-01/Women_...,2012-01-01

In [6]:
overall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   link              77 non-null     object
 1   men_wheelchair    77 non-null     object
 2   women_wheelchair  77 non-null     object
 3   men_standing      77 non-null     object
 4   women_standing    77 non-null     object
 5   month             77 non-null     object
dtypes: object(6)
memory usage: 3.7+ KB

In [7]:
col_list=overall.columns.values.tolist()
col_list

['link',
 'men_wheelchair',
 'women_wheelchair',
 'men_standing',
 'women_standing',
 'month']

In [8]:
total = []
for k in range(1,5): 
    category = col_list[k]
    category_list=overall[category].tolist()
    month_list = overall["month"].tolist()
    print(k)
#     print(category_list)
    
    for j in range(len(category_list)):
        category_list_j = requests.get(category_list[j]).text
        soup=BeautifulSoup(category_list_j,"lxml")
        ranking_table= soup.find("tbody")
        
        if (k !=4) or (j !=70) :
            td = ranking_table.find_all("td")
            
            ranks=[]
            playerids=[]
            names=[]
            countries=[]
            regions=[]
            cats=[]
            ratings=[]
            previous_ratings=[]

            if j!=76:
                for i in range(1,len(td)+1): 
                    if i%8 ==1: 
                        rank = td[i-1].text 
                        ranks=ranks+[rank]
                    elif i%8 ==2: 
                        playerid=td[i-1].text 
                        playerids=playerids+[playerid]
                    elif i%8 ==3: 
                        name=td[i-1].text 
                        names=names+[name]
                    elif i%8 ==4: 
                        country=td[i-1].text 
                        countries=countries+[country]
                    elif i%8 ==5: 
                        region=td[i-1].text 
                        regions=regions+[region]
                    elif i%8 ==6: 
                        cat=td[i-1].text 
                        cats=cats+[cat]
                    elif i%8 ==7: 
                        rating=td[i-1].text 
                        ratings=ratings+[rating]
                    else:
                        previous_rating=td[i-1].text 
                        previous_ratings=previous_ratings+[previous_rating]
            else:
                for i in range(1,len(td)+1):
                    if i%7 ==1: 
                        rank = td[i-1].text 
                        ranks=ranks+[rank]
                    elif i%7 ==2: 
                        playerid=td[i-1].text 
                        playerids=playerids+[playerid]
                    elif i%7 ==3: 
                        name=td[i-1].text 
                        names=names+[name]
                    elif i%7 ==4: 
                        country=td[i-1].text 
                        countries=countries+[country]
                    elif i%7 ==5: 
                        region=td[i-1].text 
                        regions=regions+[region]
                    elif i%7 ==6: 
                        cat=td[i-1].text 
                        cats=cats+[cat]
                    else:
                        rating=td[i-1].text 
                        ratings=ratings+[rating]
                previous_ratings = [999999999999]*int((len(td)+1)/7)

        subsubtotal=pd.DataFrame({"Rank":ranks, "Player_ID":playerids, "Name":names, "Country":countries, "Region":regions, "Class":cats, "Rating":ratings, "Previous_Rating":previous_ratings})
        subsubtotal["temp"]=j
#         print(subsubtotal)

        subtotal = pd.DataFrame({"cc":category,"mm":month_list[j]}, index =[j])
        subtotal["temp"]=j
#         print("done-subtotal")

        subtotal= pd.merge(subtotal, subsubtotal,on="temp")
        total.append(subtotal)
#         print('go-j')
#     print("go-k")

#total

1
2
3
4

In [9]:
total_final= pd.concat(total)

In [13]:
total_final.reset_index(drop=True,inplace=True)

In [14]:
total_final.to_excel("ittf_final.xlsx")

In [12]:
#有4*76个网页。。。 要抓取。。。 table ...在一张表格里面